### ISSUE TITLE
Provide a read/write mode

### ISSUE THREAD

**Issue by mcwhittemore** [mcwhittemore/staged-git-files#12]
SGF currently lets you know what files are staged. While this is helpful, knowing this often leads to the next question "can I read what is staged" and then another question "can I update what is staged".

We currently provide a `readFile` action and even an odd to configure way to have this content be returned in the JSON. That said, this reads the file on disk which is not always the same thing as what is staged.

Writing to staged files is also a bit frustrating as the file systems state does not reflect the staged state so writing to the filesystem and then calling `git add` might stage content the user did not want staged.

To fix this would we consider a `writeMode` feature that moves the current staged git state to the file system and stores the current file system state either via git-stash or some other method. When `writeMode` is closed, these two states will be reconciled and flipped.

We also need to handle the case where the program crashes and have some `on exit` code that does some sort of reconciliation (likely restore to pre-write mode).

Doing this, would also be a good chance to clean up this module a bit and have it fit to standard node practices.

My thought is that this could help land [lint-staged/#75](https://github.com/okonet/lint-staged/pull/75) which is currently blocked by:

- https://github.com/okonet/lint-staged/issues/386
- https://github.com/okonet/lint-staged/issues/387

cc @twhitbeck @okonet

**Comment by twhitbeck** [comment]
> That said, this reads the file on disk which is not always the same thing as what is staged.

Is this because a file can be partially staged?

My only other comment is that I really like the unix philosophy of "do one thing and do it well". Perhaps this functionality could reside in a new module, one that might depend on `staged-git-files`

**Comment by mcwhittemore** [comment]
Good point @twhitbeck.

Maybe we're talking about an `fs` replacement that interacts with `staged content` rather than `file-system content`. The problem with this idea is how to allow external tools to interact with this.

If I have time this weekend, I'll take a stab at what a few apis might look like. I'll drop a link to that repo in this ticket.

**Comment by mcwhittemore** [comment]
On more reflection, I agree with @twhitbeck here and so I'm going to close this issue.
