### ISSUE TITLE
Thanks ! Forked to create a commited-git-files !

### ISSUE THREAD

**Issue by clakech** [mcwhittemore/staged-git-files#5]
Hi,

FYI I was trying to publish my first npm module to list commited files diff betwee HEAD and a source branch.

My attempt is there https://www.npmjs.com/package/commited-git-files

WDYT ? I change a bit of the code and some tests too.

Thanks for your work

**Comment by mcwhittemore** [comment]
Cyril,

Sorry for now seeing this for so long. It looks like the package you published has been deprecated so I can't see it. 

Best of luck,
Matthew

**Comment by clakech** [comment]
Hello, I just rename it here https://www.npmjs.com/package/committed-git-files
